_wandb:
    value:
        cli_version: 0.24.0
        e:
            yct4n4d4rnav8zwuvc14hcmoaei24s0e:
                codePath: c:\Users\GAI\Desktop\Scott\NCA_Research\notebooks\E5_m-NCA\E5-1_m-NCA.ipynb
                codePathLocal: E5-1_m-NCA.ipynb
                cpu_count: 8
                cpu_count_logical: 16
                cudaVersion: "12.8"
                disk:
                    /:
                        total: "726082588672"
                        used: "669163876352"
                email: apc582nntscott@arch.nycu.edu.tw
                executable: c:\Users\GAI\miniconda3\envs\pytorch-py311\python.exe
                git:
                    commit: b11cbbf9b1348e13ab82fe5e2d8a5a8b19fe94e0
                    remote: https://github.com/ms-112-scott/NCA_Research.git
                gpu: NVIDIA GeForce RTX 3080 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 6144
                      memoryTotal: "17179869184"
                      name: NVIDIA GeForce RTX 3080 Laptop GPU
                      uuid: GPU-6cf8054c-6c04-c256-2ebb-8137cfc2e798
                host: GIAAIL-STRIX
                memory:
                    total: "33737932800"
                os: Windows-10-10.0.26100-SP0
                program: c:\Users\GAI\Desktop\Scott\NCA_Research\notebooks\E5_m-NCA\E5-1_m-NCA.ipynb
                python: CPython 3.11.13
                root: c:\Users\GAI\Desktop\Scott\NCA_Research\notebooks\E5_m-NCA
                startedAt: "2026-01-15T15:25:00.896197Z"
                writerId: yct4n4d4rnav8zwuvc14hcmoaei24s0e
        m: []
        python_version: 3.11.13
        t:
            "1":
                - 1
                - 41
            "2":
                - 1
                - 41
            "3":
                - 2
                - 16
            "4": 3.11.13
            "5": 0.24.0
            "8":
                - 1
                - 3
            "12": 0.24.0
            "13": windows-amd64
batch_size:
    value: 8
chn:
    value: 12
hidden_n:
    value: 96
img_size:
    value: 128
lr:
    value: 0.002
pool_reset_freq:
    value: 8
pool_size:
    value: 1024
project_name:
    value: base_texture_nca
seed:
    value: 42
step_max:
    value: 96
step_min:
    value: 32
target_img_path:
    value: dataset\lizard.png
use_gradient_checkpoint:
    value: false
